name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: TruffleHog OSS
        uses: trufflehog/trufflehog-actions@main
        with:
          repo_path: .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install backend dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r backend/requirements.txt

      - name: Run backend tests
        run: npm run test:backend

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: cd frontend && npm install

      - name/Run linter
        run: cd frontend && npx eslint .

      - name: Run frontend tests
        run: npm run test:frontend
