name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt detect-secrets

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
          cd ..

      - name: Check for secrets
        run: detect-secrets scan --all-files

      - name: Compile backend
        run: python -m compileall -q backend

      - name: Compile frontend
        run: |
          cd frontend
          npm run build --if-present
          cd ..

      - name: Run backend tests
        run: pytest backend/tests -v

      - name: Run frontend tests
        run: |
          cd frontend
          npm test --if-present
          cd ..
